from enum import Enum

class TemplateType(Enum):
    API_TEMPLATE = 'API_TEMPLATE'
    PROMPT = 'PROMPT'


class TemplateName(Enum):
    CUBEASSIST_ORCHESTRATOR_SYSTEM_PROMPT = 'CUBEASSIST_ORCHESTRATOR_SYSTEM_PROMPT'
    AGENT_SKILLS_CLASSIFIER_PROMPT = 'CUBEASSIST_ORCHESTRATOR_AGENT_SKILLS_CLASSIFIER_PROMPT'

